version: '3.3'

services:
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/build:/app/result_build/   
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: foodgram-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: foodgram-backend
    image: foodgram-backend 
    working_dir: /app  
    command: >
      sh -c "
      python foodgram/manage.py migrate &&
      python foodgram/manage.py collectstatic --noinput &&
      gunicorn foodgram.foodgram.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ../backend/:/app   
      - static:/app/static/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app/foodgram
    restart: always

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/static/
      - media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always

volumes:
  postgres_data:
  static:
  media:










  









